version: '3.1'
services:
  db:
    image: mysql
    container_name: essentials_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql

volumes:
  data:


# docker ps -> lista os conteiners que estão sendo rodados no momento
# docker-compose down -> derrubar o conteiner.
