version: '3.1'

services:
  db:
    image: mysql
    container_name: essentials_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql

volumes:
  data:

# Este arquivo docker-compose.yml define serviços para execução de um banco de dados MySQL.
# O serviço 'db' utiliza a imagem 'mysql', cria um contêiner com o nome 'essentials_mysql'.
# Define a variável de ambiente 'MYSQL_ROOT_PASSWORD' como 'root' para a senha do root do MySQL.
# Mapeia a porta '3306' do contêiner para a mesma porta no host.
# Define um volume chamado 'data' para persistir os dados do MySQL em '/var/lib/mysql'.

# Comandos úteis:
# docker ps -> lista os contêineres em execução no momento.
# docker-compose down -> desliga e remove os contêineres definidos neste arquivo docker-compose.yml.
